services:
  db:
    image: bitnami/postgresql:latest
    container_name: api-drv-pg-teste
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/bitnami/postgresql

  backend:
    build: .
    container_name: backend_app
    command: sh -c "pnpm install && pnpm prisma migrate deploy && pnpm dev"
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL= ${DATABASE_URL}

volumes:
  pgdata: